### getSpanId
GET http://localhost:8080/rpc/span
Content-Type: application/json

### getTraceId
GET http://localhost:8080/rpc/trace
Content-Type: application/json

### runAsync

GET http://localhost:8989/context/rpc/async
